
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lerha
 */
public class stokUygulaması extends javax.swing.JFrame {

    /**
     * Creates new form stokUygulaması
     */
    public stokUygulaması() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_urun_ismi = new javax.swing.JTextField();
        cb_kategori = new javax.swing.JComboBox();
        tf_fiyat = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablosu = new javax.swing.JTable();
        ekle_butonu = new javax.swing.JButton();
        guncelle_butonu = new javax.swing.JButton();
        sil_butonu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Ürün İsmi :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 110, 90, 41);

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Kategori  :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 250, 90, 40);

        jLabel3.setBackground(new java.awt.Color(153, 204, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("     Fiyat       : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 180, 100, 42);

        tf_urun_ismi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_urun_ismi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_urun_ismiActionPerformed(evt);
            }
        });
        getContentPane().add(tf_urun_ismi);
        tf_urun_ismi.setBounds(140, 110, 360, 40);

        cb_kategori.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cb_kategori.setForeground(new java.awt.Color(0, 204, 204));
        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kültür Sanat", "Yemek", "Elektronik" }));
        getContentPane().add(cb_kategori);
        cb_kategori.setBounds(150, 250, 320, 50);

        tf_fiyat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tf_fiyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fiyatActionPerformed(evt);
            }
        });
        getContentPane().add(tf_fiyat);
        tf_fiyat.setBounds(140, 180, 360, 40);

        mesaj_yazisi.setBackground(new java.awt.Color(255, 255, 255));
        mesaj_yazisi.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(255, 204, 204));
        getContentPane().add(mesaj_yazisi);
        mesaj_yazisi.setBounds(30, 320, 550, 50);

        urun_tablosu.setBackground(new java.awt.Color(153, 204, 255));
        urun_tablosu.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        urun_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün İsmi", "Kategori", "Fiyat"
            }
        ));
        urun_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablosu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 390, 605, 320);

        ekle_butonu.setBackground(new java.awt.Color(153, 204, 255));
        ekle_butonu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ekle_butonu.setForeground(new java.awt.Color(51, 204, 0));
        ekle_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Add-icon.png"))); // NOI18N
        ekle_butonu.setText("Ürün ekle");
        ekle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butonuActionPerformed(evt);
            }
        });
        getContentPane().add(ekle_butonu);
        ekle_butonu.setBounds(630, 140, 161, 42);

        guncelle_butonu.setBackground(new java.awt.Color(153, 204, 255));
        guncelle_butonu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        guncelle_butonu.setForeground(new java.awt.Color(51, 51, 255));
        guncelle_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload-icon.png"))); // NOI18N
        guncelle_butonu.setText("Ürün güncelle");
        guncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonuActionPerformed(evt);
            }
        });
        getContentPane().add(guncelle_butonu);
        guncelle_butonu.setBounds(630, 210, 161, 47);

        sil_butonu.setBackground(new java.awt.Color(153, 204, 255));
        sil_butonu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sil_butonu.setForeground(new java.awt.Color(255, 51, 51));
        sil_butonu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-edit-delete-icon.png"))); // NOI18N
        sil_butonu.setText("Ürün Sil");
        sil_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonuActionPerformed(evt);
            }
        });
        getContentPane().add(sil_butonu);
        sil_butonu.setBounds(630, 290, 161, 41);

        jLabel5.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setText("                        Stok Uygulamamıza Hosgeldiniz !");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 830, 100);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/output-onlinepngtools (1).png"))); // NOI18N
        jLabel4.setText("sdfdf");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 830, 723);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_urun_ismiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_urun_ismiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_urun_ismiActionPerformed

    private void tf_fiyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fiyatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fiyatActionPerformed

    private void ekle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butonuActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        DefaultTableModel model =(DefaultTableModel) urun_tablosu.getModel();
        
        if(tf_urun_ismi.getText().trim().equals("")||tf_fiyat.getText().trim().equals("")){
            mesaj_yazisi.setText("Boş alanları kontrol edip yeniden deneyiniz ! ");
        }else{
          Object [] eklenecek = {tf_urun_ismi.getText(),cb_kategori.getSelectedItem(),tf_fiyat.getText()};
          model.addRow(eklenecek);
        }
    }//GEN-LAST:event_ekle_butonuActionPerformed

    private void guncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonuActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        DefaultTableModel model = (DefaultTableModel) urun_tablosu.getModel();
        int secili_row = urun_tablosu.getSelectedRow();
        if(secili_row == -1){
            if(urun_tablosu.getRowCount()== 0){
                mesaj_yazisi.setText("Ürün tablosunda ürün kaydı bulunmamaktadır !");
            }else{
                mesaj_yazisi.setText("Lütfen güncellemek istediğiniz ürünün satırına tıklayınız");
            }
        }else{
            model.setValueAt(tf_urun_ismi.getText(),secili_row, 0);
            model.setValueAt(cb_kategori.getSelectedItem().toString(),secili_row, 1);
            model.setValueAt(tf_fiyat.getText(),secili_row, 2);
        mesaj_yazisi.setText("Ürün başarıyla güncellendi !");
        }
        
    }//GEN-LAST:event_guncelle_butonuActionPerformed

    private void urun_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablosuMouseClicked
       DefaultTableModel model = (DefaultTableModel)urun_tablosu.getModel();
       int secili_row = urun_tablosu.getSelectedRow();
       tf_urun_ismi.setText(model.getValueAt(secili_row, 0).toString());
       cb_kategori.setSelectedItem(model.getValueAt(secili_row, 1).toString());
       tf_fiyat.setText(model.getValueAt(secili_row, 2).toString());
    }//GEN-LAST:event_urun_tablosuMouseClicked

    private void sil_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonuActionPerformed
       DefaultTableModel model = (DefaultTableModel)urun_tablosu.getModel();
       int secili_row = urun_tablosu.getSelectedRow();
       mesaj_yazisi.setText("");
       if(secili_row == -1){
            if(urun_tablosu.getRowCount()== 0){
                mesaj_yazisi.setText("Ürün tablosunda ürün kaydı bulunmamaktadır !");
            }else{
                mesaj_yazisi.setText("Lütfen silmek istediğiniz ürünün satırına tıklayınız");
            }
        }else{
            model.removeRow(secili_row);
        mesaj_yazisi.setText("Ürün başarıyla silindi !");
        }
    }//GEN-LAST:event_sil_butonuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stokUygulaması().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_kategori;
    private javax.swing.JButton ekle_butonu;
    private javax.swing.JButton guncelle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton sil_butonu;
    private javax.swing.JTextField tf_fiyat;
    private javax.swing.JTextField tf_urun_ismi;
    private javax.swing.JTable urun_tablosu;
    // End of variables declaration//GEN-END:variables
}
